apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trivy-operator.yaml
  - namespace.yaml
  - trivy-ui-release.yaml
  - ../sources/trivy-helmrepo.yaml  
  - ../sources/trivy-ui-helmrepo.yaml  

